In [ ]:
set1=["aman", "222", 777, 400.4]

set2=tuple((set1))

set2

('aman', '222', 777, 400.4)

In [ ]:
#2.	Create a dictionary of your basic data: (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys

student={'Roll No':20245, 'First Name':'Paripoorna', 'Last Name':'D','Date of Birth':'19/11/2001' }

print(student)#printing disctionary

print("----Printing keys----")
for i in student:
  print(i)

print("----Printing the values----")
for i in student.values():
  print(i)

{'Roll No': 20245, 'First Name': 'Paripoorna', 'Last Name': 'D', 'Date of Birth': '19/11/2001'}
----Printing keys----
Roll No
First Name
Last Name
Date of Birth
----Printing the values----
20245
Paripoorna
D
19/11/2001


In [ ]:
#3.	Use rand function to generate a 2-dimensional random array with seed.

from numpy import random

a=random.randint(100, size=(2,5))

print(a)

[[90 85 16 30 95]
 [37 22 54  0 59]]


In [ ]:
#4. single random number in [0.0, 1.0]

import random
import math

x=random.uniform(0.0, 1.0)

print(x)

#absolute value of (-1234)

a=abs(-1234)

print(a)

0.36512225653146735
1234


In [ ]:
#5.return random integer between 20 and 90
y=random.randint(20,90)
print(y)

29


In [ ]:
#6. return a list of length 3

a=[11,12,13,14,15]

new_list=random.sample(a,3)
print(new_list)

random.shuffle(new_list)

print("Shuffled_list")
print(new_list)

print("random number from a list")

print(random.choice(a))


[12, 11, 13]
Shuffled_list
[12, 13, 11]
random number from a list
11


In [ ]:
#7 reading the file
write_file=open("newfile.txt", "w")

n=write_file.write("The King is Dead, Long Live The King")

write_file.close()

write_file=open("newfile.txt", "r")

print(write_file.read())

write_file.close()

The King is Dead, Long Live The King


In [ ]:
#8. use of if else

a=int(input("enter an integer:- "))

#checking the number is even or odd (use of ifelse)

if (a%2==0):
  print(str(a)+" is an even number")
else:
  print(str(a)+" is an odd number")

#sum of the digits of a (use of while loop)

sum=0
while a!=0:
  p=a%10
  
  sum=sum+p
  a=int(a/10)

print("sum of the digits: ", sum)




enter an integer:- 345
345 is an odd number
5
4
3
sum of the digits:  12


In [ ]:
#9.
a="The King is Dead, Long Live The King"
print(a)
print(a[0])
print(a[2:5])
print(a[2:])
print(a.split())

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [ ]:
#10.
import numpy as np

a=[1,2,3,4,5]

arr=np.array(a)

print(arr[0:2])

[1 2]


In [ ]:
#11.multi dimensional array

arr=np.array([[1,2,3],[4,5,6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
#12.
print(arr[1:2]) #displaying the 2nd row
print(arr[:, 1])
print(arr.size) #length of the array

[[4 5 6]]
[2 5]
6


In [ ]:
#13. reshaping an array 1-d to 2-d

arr1=np.arange(1,11)

reshaped_array=arr1.reshape(5,2)

print(reshaped_array) 

print("Transpose of an array")

transposed_array=reshaped_array.T

print(transposed_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transpose of an array
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [ ]:
#14. creating an array from a list of 1, 2 and 3

a=[1,2,3]

arr2=np.array(a)

print(arr2)

[1 2 3]


In [ ]:
#15.fill an array with as ingle value

a=np.array([1,2,3])

a.fill(9)

print(a)

[9 9 9]


In [ ]:
#16.array sum

arr3=np.array([2,4,5])

print(arr3.sum())

11


In [ ]:
#17. array product

arr4=np.array([77,74,75])

print(arr4.prod())

427350


In [ ]:
#18.
arr5=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("mean", arr5.mean())
print("variance", arr5.var())
print("Maximum", arr5.max())
print("Minimum", arr5.min())
print("argmin", arr5.argmin())
print("median", np.median(arr5))
print("argmax", arr5.argmax())
print("standard deviation", np.std(arr5))

mean 12.461538461538462
variance 367.32544378698225
Maximum 56
Minimum 1
argmin 1
median 2.0
argmax 12
standard deviation 19.165736192147232


In [ ]:
#19. printing unique elements and sorting it out
arr6=np.array([1, 1, 4, 5, 5, 5, 7] )
print(np.unique(arr6))
print(np.sort(arr6))


[1 4 5 7]
[1 1 4 5 5 5 7]


In [ ]:
#20. product of two arrays

arr7=np.array([1,2,3])
arr8=np.array([0,1,1])

print("dot product of two arrays:-", arr7*arr8)


dot product of two arrays:- [0 2 3]


In [ ]:
#21. printing eigen values and eigen vectors of a matrix a
from numpy.linalg import eig
A=np.array([[2,-12],[1,-5]])

val,vec=eig(A)

print("Eigen value:- ", val)
print("Eigen vector:- ", vec)

Eigen value:-  [-1. -2.]
Eigen vector:-  [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [ ]:
#22. prining correlation coefficient of two matrices

arr8=np.array([11,22,11,31])
arr9=np.array([25,33,31,28])

print(np.corrcoef(arr8, arr9))

[[1.         0.15997968]
 [0.15997968 1.        ]]
